name: Staging CI

on:
  pull_request:
    branches: [staging, master]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: ./.github/actions/cache
        with:
          name: 'node-modules_${{ github.run_id }}'

      - uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.SSH_GITHUB_KEY }}

      - name: Install dependencies
        run: npm ci


  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: ./.github/actions/cache
        with:
          name: 'node-modules_${{ github.run_id }}'
      - run: npm run lint

  security:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --all-projects --severity-threshold=high


  tsc:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: ./.github/actions/cache
        with:
          name: 'node-modules_${{ github.run_id }}'
      - run: npm run tsc

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: ./.github/actions/cache
        with:
          name: 'node-modules_${{ github.run_id }}'
      - run: npm run jest --runInBand

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: ./.github/actions/cache
        with:
          name: 'node-modules_${{ github.run_id }}'
      - run: npm run build
